# Generated by Django 4.1.5 on 2023-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0002_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock')], max_length=5),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
